# Site settings
title: Swisher Republic
email: Michael.V.Swisher@colorado.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  misw9423

# Build settings
markdown: kramdown
